site_name: imdb
site_description: IMDB Movies Ratings
repo_url: https://github.com/rajat2814/imdb
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/rajat2814">rajat2814</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
