# Generated by Django 3.0.8 on 2020-07-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.FloatField(default=0.0)),
                ('imdb_score', models.FloatField(default=0.0)),
                ('name', models.TextField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Director')),
                ('genre', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
